/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eemil
 */
public class Laskin extends javax.swing.JFrame {

    /**
     * Creates new form Laskin
     */
    
    // tehdään muuttujat jotka tunnistaa numerot, vastauksen ja laskenna.
    double num,ans;
    int laskenta;
    
    public Laskin() {
        initComponents();
        this.setTitle("Tervetuloa laskimeen");
    }
    
    // LaskuOperaatio() metodi tekee laskukaavat
    public void laskuOperaatio() {
        switch(laskenta){
            case 1: // Pluslasku
                ans = num + Double.parseDouble(jtxtAlkunaytto.getText());
                jtxtAlkunaytto.setText(Double.toString(ans));
                break;
                
            case 2: // Miinuslasku
                ans = num - Double.parseDouble(jtxtAlkunaytto.getText());
                jtxtAlkunaytto.setText(Double.toString(ans));
                break;
                
            case 3: // Kertolasku
                ans = num * Double.parseDouble(jtxtAlkunaytto.getText());
                jtxtAlkunaytto.setText(Double.toString(ans));
                break;
             
            
            case 4: // Jakolasku
                ans = num / Double.parseDouble(jtxtAlkunaytto.getText());
                jtxtAlkunaytto.setText(Double.toString(ans));
                break; 
            
        } 
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtAlkunaytto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jlblOtsikko = new javax.swing.JLabel();
        jButtonC = new javax.swing.JButton();
        jButtonPiste = new javax.swing.JButton();
        jButtonPlussa = new javax.swing.JButton();
        jButtonMiinus = new javax.swing.JButton();
        jButtonKerto = new javax.swing.JButton();
        jButtonJako = new javax.swing.JButton();
        jButtonYhteenlasku = new javax.swing.JButton();
        jButtonPyyhi = new javax.swing.JButton();
        jlblLasku = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jtxtAlkunaytto.setEditable(false);
        jtxtAlkunaytto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtAlkunaytto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtAlkunaytto.setText("0");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("0");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jlblOtsikko.setFont(new java.awt.Font("Nimbus Sans", 1, 14)); // NOI18N
        jlblOtsikko.setText("Laskin");

        jButtonC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonPiste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPiste.setText(".");
        jButtonPiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPisteActionPerformed(evt);
            }
        });

        jButtonPlussa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPlussa.setText("+");
        jButtonPlussa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlussaActionPerformed(evt);
            }
        });

        jButtonMiinus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonMiinus.setText("-");
        jButtonMiinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMiinusActionPerformed(evt);
            }
        });

        jButtonKerto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonKerto.setText("*");
        jButtonKerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKertoActionPerformed(evt);
            }
        });

        jButtonJako.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonJako.setText("/");
        jButtonJako.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJakoActionPerformed(evt);
            }
        });

        jButtonYhteenlasku.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonYhteenlasku.setText("=");
        jButtonYhteenlasku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYhteenlaskuActionPerformed(evt);
            }
        });

        jButtonPyyhi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPyyhi.setText("<--");
        jButtonPyyhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPyyhiActionPerformed(evt);
            }
        });

        jlblLasku.setForeground(new java.awt.Color(255, 102, 204));
        jlblLasku.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("(-)");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblOtsikko)
                .addGap(18, 18, 18)
                .addComponent(jlblLasku, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jtxtAlkunaytto, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonPiste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPlussa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonMiinus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonJako, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonKerto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonYhteenlasku, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPyyhi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblLasku, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblOtsikko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtAlkunaytto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButtonPlussa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButtonMiinus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButtonKerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButtonC)
                    .addComponent(jButtonPiste)
                    .addComponent(jButtonJako))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonYhteenlasku)
                    .addComponent(jButtonPyyhi)
                    .addComponent(jButton11))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // equals komennolla voidaan saada selville että toteuttaako se if lausekkeen ja tässä tapauksessa, jos näyttö alkaa nollalla, niin se aloittaa sillä numerolla.
    // Tehdään näppäimet jotka tunnistavat numerot ja merkit käyttämällä setText()
    // getText() voidaan yhdistää monta numero kerrallaan
    
    // Tehtään napit joilla pystyy antamaan tietyn numeron
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("1");
        } else {
            jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "1");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("2");
        } else {
            jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "2");
        }
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
             jtxtAlkunaytto.setText("3");
        } else {
            jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "3");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("4");
        } else {
            jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "4");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("5");
        } else {
            jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "5");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("6");
        } else {
            jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "6");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("7");
        } else {
            jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "7");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("8");
        } else {
           jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "8"); 
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("9");
        } else {
           jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "9"); 
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("0");
        } else {
           jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + "0"); 
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonPisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPisteActionPerformed
        // indexOf palauttaa arvonaan tiedon, monentenako merkkijonossa on ensimmäinen parametrina annettu merkki.
        // Mahdollistaa yhden pisteen kirjoittamisen ainoastaan.
        if (((jtxtAlkunaytto.getText().indexOf(".")) == -1)) {
        jtxtAlkunaytto.setText(jtxtAlkunaytto.getText() + ".");
    } 
        
    }//GEN-LAST:event_jButtonPisteActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        // pyyhkii kaikki arvot textfieldistä ja labelistä.
        jtxtAlkunaytto.setText("");
        jlblLasku.setText("");
    }//GEN-LAST:event_jButtonCActionPerformed
        // num muuttujalla saadaan textfieldiin tunnistettuu numerot ja samalla tietyt laskukaavat.
    private void jButtonPlussaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlussaActionPerformed
        num = Double.parseDouble(jtxtAlkunaytto.getText());
        laskenta = 1;
        jtxtAlkunaytto.setText("");
        jlblLasku.setText(num + "+");
        
    }//GEN-LAST:event_jButtonPlussaActionPerformed

    private void jButtonMiinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMiinusActionPerformed
        num = Double.parseDouble(jtxtAlkunaytto.getText());
        laskenta = 2;
        jtxtAlkunaytto.setText("");
        jlblLasku.setText(num + "-");
        
    }//GEN-LAST:event_jButtonMiinusActionPerformed

    private void jButtonKertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKertoActionPerformed
        num = Double.parseDouble(jtxtAlkunaytto.getText());
        laskenta = 3;
        jtxtAlkunaytto.setText("");
        jlblLasku.setText(num + "*");
        
    }//GEN-LAST:event_jButtonKertoActionPerformed

    private void jButtonJakoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJakoActionPerformed
        num = Double.parseDouble(jtxtAlkunaytto.getText());
        laskenta = 4;
        jtxtAlkunaytto.setText("");
        jlblLasku.setText(num + "/");
        
    }//GEN-LAST:event_jButtonJakoActionPerformed

    private void jButtonPyyhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPyyhiActionPerformed

        //length() metodilla saadaan merkkien määrä selville ja voidaan poistaa yksi merkki kerrallaan
        int length = jtxtAlkunaytto.getText().length();
        int number = jtxtAlkunaytto.getText().length() - 1;
        String store;
        
        //StringBuilder pystytään tallentamaan merkkijonoja
        //String store:lla pystytään muuttamaan takaisin doublesta String muotoon.
        if (length > 0) {
            StringBuilder back = new StringBuilder(jtxtAlkunaytto.getText());
            back.deleteCharAt(number);
            store=back.toString();
            jtxtAlkunaytto.setText(store);
        }
    }//GEN-LAST:event_jButtonPyyhiActionPerformed

    private void jButtonYhteenlaskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYhteenlaskuActionPerformed
        // Painike tuloksen saamiseksi.
        // Samalla muutettiin tietyt arvot kuten NaN ja Infinity on muutettu eriarvoilla. 
        // laskuOperaatio() metodilla saadaan yhteenlaskunappi toimimaan
        laskuOperaatio();
        jlblLasku.setText("");
        
        if (jtxtAlkunaytto.getText().equals("NaN")) {
            jtxtAlkunaytto.setText("Nollalla ei voi jakaa :)");
        } else if (jtxtAlkunaytto.getText().equals("Infinity")) {
            jtxtAlkunaytto.setText("∞");
        } else if (jtxtAlkunaytto.getText().equals("-Infinity")) {
            jtxtAlkunaytto.setText("-∞");
        }
    }//GEN-LAST:event_jButtonYhteenlaskuActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (jtxtAlkunaytto.getText().equals("0")) {
            jtxtAlkunaytto.setText("-");
        } 
    
        // indexOf palauttaa arvonaan tiedon, monentenako merkkijonossa on ensimmäinen parametrina annettu merkki
        // Mahdollistaa yhden miinus merkin kirjoittamisen.
        if (((jtxtAlkunaytto.getText().indexOf("-")) == -1)) {
            jtxtAlkunaytto.setText("-" + jtxtAlkunaytto.getText());
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laskin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laskin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laskin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laskin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laskin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonJako;
    private javax.swing.JButton jButtonKerto;
    private javax.swing.JButton jButtonMiinus;
    private javax.swing.JButton jButtonPiste;
    private javax.swing.JButton jButtonPlussa;
    private javax.swing.JButton jButtonPyyhi;
    private javax.swing.JButton jButtonYhteenlasku;
    private javax.swing.JLabel jlblLasku;
    private javax.swing.JLabel jlblOtsikko;
    private javax.swing.JTextField jtxtAlkunaytto;
    // End of variables declaration//GEN-END:variables

}
